### ISSUE TITLE
Remove coloring in some buttons

### ISSUE THREAD

**Issue by N6REJ** [N6REJ/embryo#63]
_From @N6REJ on February 1, 2015 21:20_

jbackbone.css line 254 has more coloring, remove it.
```css
.mailto-close > a,#pop-print.btn > a,#mailto-window button {
/*background-color:#fff;*/
/*border-color:#ccc;*/
	display:inline-block;
	padding:6px 12px;
	margin-bottom:0;
	font-size:14px;
	font-weight:400;
	line-height:1.42857143;
	text-align:center;
	white-space:nowrap;
	vertical-align:middle;
	cursor:pointer;
	-webkit-user-select:none;
	-moz-user-select:none;
	-ms-user-select:none;
	user-select:none;
	background-image:none;
	border:1px solid #ccc;
	border-radius:4px;
}
```

_Copied from original issue: N6REJ/ae-template#60_
